{% set name = "pygrametl" %}
{% set version = "2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygrametl-{{ version }}.tar.gz
  sha256: 8c7f3afa4e8a591110e72fe17d934c5e04bd465e90da9379b2e39603eb293cbb

build:
  number: 1
  noarch: python
  entry_points:
    - dttr = pygrametl.drawntabletesting.dttr:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pygrametl
    - pygrametl.drawntabletesting
  commands:
    - pip check
    # - dttr --help return non-zero
  requires:
    - pip

about:
  home: http://pygrametl.org/
  license: BSD-2-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: ETL programming in Python

extra:
  recipe-maintainers:
    - mariusvniekerk
