{% set version = "2.6" %}
{% set name = "pygrametl" %}

package:
  name: pygrametl
  version: {{ version }}

source:
  fn: pygrametl-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7671c58bb9ddf4d8ffb565fa9cb29f5e0484a7dc8c88f30bcb820370e69e5a52

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pygrametl

about:
  home: http://pygrametl.org/
  license: BSD-2-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'ETL programming in Python'

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
