{% set version = "2.7" %}
{% set name = "pygrametl" %}

package:
  name: pygrametl
  version: {{ version }}

source:
  fn: pygrametl-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c7f3afa4e8a591110e72fe17d934c5e04bd465e90da9379b2e39603eb293cbb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pygrametl

about:
  home: http://pygrametl.org/
  license: BSD-2-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: ETL programming in Python

extra:
  recipe-maintainers:
    - mariusvniekerk
