appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OyO8nCRmvpACvDo69Ct3PqHMTtEZWLLenjEihvBVaHMFGQHN0m9banBf6G6v5cl8qfOW0QWNA7UUtYdafLFO9vdSOKfNdbl6AWSpjuRD1hFdAk0nGkfLjhU1UpDL1Lwmez5a1r2xKEdEFgvTWab/xy6pLHyd27idVTUEGV6weXAoEui/OqQdvkUMDg4IGnBuoPGMf06/kZTGKZU3DyaHuAosJ8HEsmTYRUyVN1YiVP5iMoyhoxpU9TAOrs+kPrJKZ7qh3XW8sl/UyWk7Fvl3wvKvaWLRNaZk+J54ioYn883hqksUy70s6dYeT3PTduLGC5ATjL3ku1qNeSvpgDFG0eRRE+x1wQdM3Rdvg+hRcrmQGU1GkXksiecgvaj06lTR2TazRU3fYoJJxCQh8MDZKfbOlhoh+dnNy38BMqDjoQgntFbJuKhNHimkYEWgl9Lq1/rFI7rxPjH86uTZQswVrZgNa6edWU9vM5KfJwJMcQmpWKxm88oFh2ty5XJTRH+SFG+AzGpF7KVmxdN2vu/QU7NdpIjXYKYLPsHm0j90iHP+WNPYMPKqhRwZwLqUDj6o116QRj2vqibJOtORqqciRTZhRb2dsV4H7igWMDslVuTCm6fQ/unblozGojzH8QDL6NuBjaPCNzsE0ujVXOV+SRgAyifPwUdsmukpYDjrMjA=}
bot:
  automerge: true
